1. Import the &quot;numpy&quot; library as &quot;np&quot;.





In [0]:
import numpy as np

2. Create an array of shape (2, 3, 4) of zeros.

In [18]:
(np.zeros(shape = (2,3,4)))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

3. Create an array of shape (2, 3, 4) of ones

In [19]:
np.ones(shape = (2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

4. Create an array with values 0 to 999 using the "np.arange" function

In [20]:
np.arange(1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

5.Create an array from the list [2, 3.2, 5.5, -6.4, -2.2, 2.4] and assign it to the variable &quot;a&quot;

In [22]:
a = np.array([2,3.2,5.5,-6.4,-2.,2.4])
a

array([ 2. ,  3.2,  5.5, -6.4, -2. ,  2.4])

6. Do you know what a[1] will equal? Print it to see


In [23]:
a[1]

3.2

7. Create a 2-D array from the following list and assign it to the variable "a": [[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]]


In [24]:
a = np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4], [1, 22, 4, 0.1, 5.3, -9], [3, 1, 2.1, 21, 1.1, -2]])
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2,  2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

8.  Can you guess what the following slices are equal to? Print them to check your understanding. a[:, 3] a[1:4, 0:4] a[1:, 2]


In [39]:
print(a[:, 3], "\n")
print(a[1:4, 0:4], "\n")
print(a[1:, 2])

[-6.4  0.1 21. ] 

[[ 1.  22.   4.   0.1]
 [ 3.   1.   2.1 21. ]] 

[4.  2.1]


9. Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the variable "arr".Print the shape of the array. Print the size of the array. Print the maximum and minimum of the array


In [77]:

arr = np.array((range(4),range(10,14)) , dtype=int)
print(arr)
print("shape: ",arr.shape)
print("size : ",np.size(arr))
print("max : ",np.max(arr))
print("min : " , np.min(arr))

[[ 0  1  2  3]
 [10 11 12 13]]
shape:  (2, 4)
size :  8
max :  13
min :  0


10. Continue to use the array "arr" as defined above.Print the array re-shaped to (2, 2, 2).Print the array transposed.Print the array flattened to a single dimension. Print the array converted to floats

In [67]:
print("reshape : " , arr.reshape(2,2,2) , "\n")
print("transpose : " , arr.transpose() , "\n")
print("1 dim : " , arr.flatten() ,  "\n")
print("changed data type: " , arr.astype(float))

reshape :  [[[ 0  1]
  [ 2  3]]

 [[10 11]
  [12 13]]] 

transpose :  [[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]] 

1 dim :  [ 0  1  2  3 10 11 12 13] 

changed data type:  [[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]]


11.  Create an an array counting from 1 to 20 inclusive


In [68]:
np.array(range(1,21))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

12. The array of multiples of 3 greater than 0 and less than 30


In [76]:
a = np.array(range(1,10))
print(a*3)

[ 3  6  9 12 15 18 21 24 27]


13. The array of 8 equally spaced floats x where 0 ≤ x ≤ 1

In [81]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

14. se np.arange and reshape to create the array A = [[1 2 3 4] [5 6 7 8]]

In [86]:
 A = np.arange(1,9)
 A.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

15. . Use np.array to create the array B = [1 2]

In [88]:
B = np.array([1,2])
B

array([1, 2])

16. Use broadcasting to add B to A to create the final array A + B

In [89]:
A[:, np.newaxis] + B    

array([[ 2,  3],
       [ 3,  4],
       [ 4,  5],
       [ 5,  6],
       [ 6,  7],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10]])